# Generated by Django 3.0.6 on 2020-04-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipe',
            name='receipe_type',
            field=models.TextField(default='NA'),
        ),
    ]
